// Create web server
// npm install express
// npm install body-parser
// npm install express-session
// npm install cookie-parser
// npm install ejs
// npm install mysql
// npm install nodemon
// npm install express-fileupload
// npm install fs
// npm install express-session
// npm install express-flash
// npm install express-validator
// npm install express-mysql-session
// npm install nodemailer
// npm install nodemailer-smtp-transport
// npm install nodemailer-express-handlebars
// npm install bcrypt
// npm install express-myconnection